twig:
<<<<<<< ours
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    # Variable globales pour charger les catégories dans un template twig plutôt que dans le controller
    globals:
        categories:
            '@App\Repository\CategoriesRepository'
    paths:
        'assets/images': images
=======
    file_name_pattern: '*.twig'
>>>>>>> theirs

when@test:
    twig:
        strict_variables: true
